#pragma once
#define TEX_STAGE31 1
#define TEX_STAGE32 2
#define TEX_STAGE33 3
#define TEX_PLAYER 4
#define TEX_SPARTA 5

#define PLAYER_SLASH_FRAME 7
#define PLAYER_RUNNING_FRAME 4
#define PLAYER_JUMPING_FRAME 2
#define SPARTA_FRAME 15

#define GRID_ROWS 5
#define GRID_COLUMNS 5
#define PLAYER_RUN_VELOCITY 90
#define PLAYER_JUMP_ACCELERATEX 15
#define GRAVITY 12
#define PLAYER_MIN_JUMP_VELOCITY 270
#define PLAYER_MAX_FALLING_VELOCITY -270

#define PLAYER_OFFSET_GROUND PLAYER_MIN_JUMP_VELOCITY * 1.0 / 60

