#pragma once
#define TEX_STAGE31 1
#define TEX_STAGE32 2
#define TEX_STAGE33 3
#define TEX_PLAYER 4
#define TEX_SPARTA 5

#define GRID_ROWS 5
#define GRID_COLUMNS 5
#define PLAYER_RUN_VELOCITY 135
#define PLAYER_JUMP_ACCELERATEX 15
#define PLAYER_JUMP_ACCELERATEY 50
#define PLAYER_MIN_JUMP_VELOCITY 550
#define PLAYER_MAX_FALLING_VELOCITY -550
